version: '3.8'

services:
  ocb-nextjs:
    build:
      context: ../../../
      dockerfile: deployment/staging/docker/next/Dockerfile
    container_name: ocb-nextjs
    ports:
      - "3000:3000"
    environment:
      - ENV=staging
    depends_on:
      - ocb-ws-server
      - ocb-json-server

  ocb-ws-server:
    build:
      context: ../../../
      dockerfile: deployment/staging/docker/ws-server/Dockerfile
    container_name: ocb-ws-server
    ports:
      - "3010:3010"

  ocb-json-server:
    build:
      context: ../../../
      dockerfile: deployment/staging/docker/json-server/Dockerfile
    container_name: ocb-json-server
    ports:
      - "3020:3020"

volumes:
  db_data:
