version: '3.8'

services:
  ocb-nextjs:
    build:
      context: ../../../
      dockerfile: deployment/staging/docker/next/Dockerfile
    container_name: ocb-nextjs
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=staging
      - WS_SERVER_URL=${STG_WS_SERVER_URL}
      - JSON_SERVER_URL=${STG_WS_SERVER_URL}
    depends_on:
      - ocb-ws-server
      - ocb-json-server

  ocb-ws-server:
    build:
      context: ../../../
      dockerfile: deployment/staging/docker/ws-server/Dockerfile
    container_name: ocb-ws-server
    ports:
      - "4010:3010"

  ocb-json-server:
    build:
      context: ../../../
      dockerfile: deployment/staging/docker/json-server/Dockerfile
    container_name: ocb-json-server
    ports:
      - "4020:3020"

volumes:
  db_data:
